### PR TITLE
Testing out the paywall

### PR DESCRIPTION
**Pull request by ecurrencyhodler**
I think it'd be cool to see if we can test out this Lightning Paywall for a Lightning start up I met on reddit. We can publish the notes we make when we collaborate for the Socratic Seminar reading list each month and place it behind the paywall so it's not just links to documents but in depth information about topics. The goal of this wouldn't be to generate revenue but to see if we can get some traction and test the market for them a bit.

In order to implement the paywall, it looks like all we have to do is copy and paste this script onto a new page. But I'm not sure how the website will process this PR because it looks like it takes markdown and translates it into HTML/CSS for the site. 

Can you take a look at this? 

You can also check out what it looks like on this codepen.
https://codepen.io/ecurrencyhodler/pen/ZEQPXMW

Thanks.

### CODE REVIEW

**Comment by notmandatory** [comment]
I added a fix so this basically works, but still doesn't look quite right, it looks like a full page inside a page. Are there any docs on how to create the encrypted page data? I checked the [Satotious website](https://satotious.com/index.html) but couldn't find anything. We need to just have the script hide the main <section> of the page, not the header and footer.

If you install zola you can see how it works with the command: 
```
zola serve
```

**Comment by notmandatory** [comment]
This will also need some CSS styling to make it look good once the basic script is working right.

**Comment by ecurrencyhodler** [comment]
To generate it, you have to create an account through their website and submit the HTML to generate the script. I'll try resubmitting the script without the header/footer.

I'm not sure how would the CSS work though.

**Comment by notmandatory** [comment]
@ecurrencyhodler this is ready to take a look at on your local system (`git checkout ecurrencyhodler-patch-1`). If it looks good I'll merge it.

**Pull request merged**
